### ISSUE TITLE
Support image

### ISSUE THREAD

**Issue by thangisme** [lopul/MemorySurfer#1]
This web app is pretty simple and good. I had trouble using it at first, though. Do you plan to add image or other html element support?

**Comment by lopul** [comment]
yes - i plan HTML (it is roughly replacing the <textarea> with an <div>, and not escaping the '<' and '&' characters...). images currently can't stored in the Qustion-Answer (.imsf) - (but may be linked from the HTML [if it would be implemented]). not sure how long it will take...

**Comment by thangisme** [comment]
> yes - i plan HTML (it is roughly replacing the <textarea> with an <div>, and not escaping the '<' and '&' characters...). images currently can't be stored in the Qustion-Answer-file (.imsf) - (but may be linked from the HTML [if it would be implemented]). not sure how long it will take...

Btw, if you ever add custom CSS support, I'd definitely contribute to the project.
I'm really appreciate your work!

**Comment by lopul** [comment]
> 
> Btw, if you ever add custom CSS support, I'd definitely contribute to the project.
>
for HTML some kind of CSS support is necessary - currently i think some kind of inline &lt;style> template (per deck/category) (which is inserted when ever a card is displayed) - so far for the theory...

**Comment by lopul** [comment]
a card has now a HTML check box - if checked the card is learned in HTML (editing / searching is still TXT). there is no validation of the HTML. &amp; and &lt; must be escaped. to display a image SVG might be possible.

**Comment by thangisme** [comment]
> a card has now a HTML check box - if checked the card is learned in HTML (editing / searching is still TXT). there is no validation of the HTML. '&' and '<' must be escaped. to display a image SVG might be possible?

Why not validate HTML?

**Comment by lopul** [comment]
because it is too complex (CSS, JavaScript, SVG, ...)
